### ISSUE TITLE
不能回车搜索

### ISSUE THREAD

**Issue by Supremesir** [qoli/aDict-for-mac-Release#1]
我在使用过程中遇到一点问题，
目前的查询逻辑是根据输入字符的停顿时间来自动触发查询吗？回车的功能貌似是全选？不能根据回车来查询吗？
很多时候我还没有输入完就已经触发了查询，但我输完之后又不能按回车来搜索。有的时候输入完了，软件没有自动查询，但又没有触发查询的快捷键。是否有必要添加一个查询的快捷键呢？

**Comment by qoli** [comment]
text onchange 觸發的。
請告知你的輸入法的名字，或者嘗試一下英文輸入法。

另外，目前反饋方式以 Telegram Group 為主。

往後的更新追加一下按回車後再度觸發搜索。

t.me/RonnieApps
